# Generated by Django 2.2 on 2021-08-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_books', '0002_auto_20210814_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
